/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#232D43",
        "secondary": "#232D43",
        "accent": "#A38048",
        "gold": "#A38048",
        "navy": "#232D43",
        "tertiary": "#232D43",
        "on-background": "#232D43",
        "surface-container-low": "#f6f3ee",
        "on-primary-container": "#232D43",
        "on-tertiary-fixed": "#232D43",
        "error-container": "#ffdad6",
        "surface-dim": "#dadadb",
        "surface": "#faf9f6",
        "on-secondary-container": "#232D43",
        "on-surface": "#232D43",
        "inverse-surface": "#232D43",
        "tertiary-fixed-dim": "#cac6c3",
        "inverse-on-surface": "#f0f1f2",
        "surface-variant": "#eee8df",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf9f6",
        "surface-container-high": "#ebe5dc",
        "on-secondary-fixed": "#232D43",
        "primary-fixed": "#e5e2e1",
        "on-surface-variant": "#232D43",
        "on-primary-fixed-variant": "#232D43",
        "on-secondary-fixed-variant": "#232D43",
        "inverse-primary": "#c8c6c5",
        "primary-container": "#232D43",
        "primary-fixed-dim": "#c8c6c5",
        "background": "#faf9f6",
        "on-tertiary-fixed-variant": "#232D43",
        "on-tertiary-container": "#232D43",
        "on-primary": "#ffffff",
        "surface-container": "#eee8df",
        "tertiary-container": "#232D43",
        "outline": "#A38048",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e6e1df",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e2dad0",
        "on-primary-fixed": "#232D43",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "outline-variant": "#e2dad0",
        "secondary-fixed-dim": "#c6c5cf",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "secondary-container": "#e3e1ec",
        "secondary-fixed": "#e3e1ec"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "unit": "4px",
        "max-width": "1280px",
        "margin-mobile": "16px",
        "xl": "40px",
        "gutter": "24px",
        "xs": "4px",
        "lg": "24px",
        "margin-desktop": "64px",
        "md": "16px"
      },
      fontFamily: {
        "sans": ["Montserrat", "sans-serif"],
        "display": ["Montserrat", "sans-serif"],
        "h2": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "h1": ["Montserrat", "sans-serif"],
        "h1-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "caption": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "display": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "h1": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h1-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
